storage:
  # YAML, MYSQL, SQLITE, JSON
  type: "YAML"
  #
  # Если type установлен на YAML
  #
  # Если у вас большой онлайн, то рекомендуется включить эту опцию чтобы не нагружать сервер при работе с YAML
  # true - Будет моментально сохранять данные в файл при изменении
  # false - Будет сохранять данные в файл только при перезагрузке сервера
  # Если у вас маленький онлайн, то можно оставить false
  yaml-force-save: false
  # Данные ниже используются только для MYSQL
  host: "localhost"
  port: 3306
  database: "treexbuyer"
  username: "root"
  password: ""

debug: false

items-prices-file: priceItem.yml

autobuy:
  delay: 60  # В тиках. Как часто будет срабатывать АвтоСкупка. По умолчанию 60 - 3 секунды
  actions:
    - '[MESSAGE] &8&l> &fАвтоматически продано предметов на сумму &a&l%sell_pay%&f, и &c&l%sell_score% &fочков.'
  disabled-worlds:
    - duel-1
    - duel-2
  status:
    enable: "&aВключён"
    disable: "&cВыключен"

# за каждые 100 очков игрок будет получать +0.1 к коэффициенту
score-to-multiplier-ratio:
  scores: 100
  coefficient: 0.01

# максимальный коэффициент (без учёта донатных бустов)
max-legal-coefficient: 3
default-coefficient: 1
# если true, донатные бусты будут обходить значение в max-legal-coefficient
boosters_except_legal_coefficient: true
booster:
  donat-1: # имя (может быть любым)
    permission: 'buyer.boost.donat1' # (пермишен по которому будет определяться наличие буста)
    external-coefficient: 0.5

