name: TreexBuyer
version: '3.2'
main: me.jetby.treexBuyer.Main
api-version: '1.16'
load: POSTWORLD
authors: [ MrJetby ]
website: https://dsc.gg/treexstudio
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  treexbuyer:
    aliases:
      - tb
      - tbuyer